### ISSUE TITLE
Warning with scapy: No route found for IPv6 destination

### ISSUE THREAD

**Issue by nelimee** [louisabraham/DofLog#2]
At every startup on my computer, a warning appears:
"WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6"

**Comment by louisabraham** [comment]
Could you try that? https://stackoverflow.com/questions/24812604/hide-scapy-warning-message-ipv6

**Comment by nelimee** [comment]
Fixed with the trick in the SO link.
